CREATE TABLE TREE_PLANTING_PROJECTS_DONORS (
  donor_id INTEGER NOT NULL,
  planting_id INTEGER NOT NULL,
  PRIMARY KEY (donor_id, planting_id),
  FOREIGN KEY (donor_id) REFERENCES DONOR(PersonID),
  FOREIGN KEY (planting_id) REFERENCES TREE_PLANTING_PROJECTS(planting_id)
);


ALTER TABLE EMPLOYEE ADD forest_id INTEGER;
ALTER TABLE EMPLOYEE ADD FOREIGN KEY (forest_id) REFERENCES FORESTS(forest_id);


ALTER TABLE DONATION ADD planting_id INTEGER;
ALTER TABLE DONATION ADD FOREIGN KEY (planting_id) REFERENCES TREE_PLANTING_PROJECTS(planting_id);


ALTER TABLE TREE_PLANTING_PROJECTS ADD donor_id INTEGER;
ALTER TABLE TREE_PLANTING_PROJECTS ADD FOREIGN KEY (donor_id) REFERENCES DONOR(PersonID);


ALTER TABLE TREES ADD forest_id INTEGER;
ALTER TABLE TREES ADD FOREIGN KEY (forest_id) REFERENCES FORESTS(forest_id);


ALTER TABLE RESEARCH_STATIONS ADD forest_id INTEGER;
ALTER TABLE RESEARCH_STATIONS ADD FOREIGN KEY (forest_id) REFERENCES FORESTS(forest_id);


ALTER TABLE EDUCATION_PROGRAMS ADD station_id INTEGER;
ALTER TABLE EDUCATION_PROGRAMS ADD FOREIGN KEY (station_id) REFERENCES RESEARCH_STATIONS(station_id);
